// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Aktiviteti", b =>
                {
                    b.Property<Guid>("AktivitetiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataMbajtjes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmriSalles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AktivitetiId");

                    b.ToTable("Aktivitetet");
                });

            modelBuilder.Entity("Domain.AppAdmin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Domain.Autobusi", b =>
                {
                    b.Property<Guid>("AutobusiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OraNisjes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brendi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nrPasagjereve")
                        .HasColumnType("int");

                    b.Property<string>("targat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vitiProdhimit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AutobusiId");

                    b.ToTable("Autobusat");
                });

            modelBuilder.Entity("Domain.Familja", b =>
                {
                    b.Property<Guid>("FamiljaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NxenesiId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrindiId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FamiljaId");

                    b.HasIndex("NxenesiId");

                    b.HasIndex("PrindiId");

                    b.ToTable("Familjet");
                });

            modelBuilder.Entity("Domain.FeedbackToNxenesi", b =>
                {
                    b.Property<Guid>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MessageSentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NxenesiEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfesoriId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedbackID");

                    b.HasIndex("ProfesoriId");

                    b.ToTable("FeedbackToNxenesit");
                });

            modelBuilder.Entity("Domain.Klasa", b =>
                {
                    b.Property<Guid>("KlasaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParaleljaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SallaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Viti")
                        .HasColumnType("int");

                    b.HasKey("KlasaId");

                    b.HasIndex("ParaleljaId");

                    b.HasIndex("SallaId")
                        .IsUnique();

                    b.ToTable("Klasat");
                });

            modelBuilder.Entity("Domain.Kontakti", b =>
                {
                    b.Property<Guid>("KontaktiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEDergimit")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReply")
                        .HasColumnType("bit");

                    b.Property<string>("Mesazhi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrindiId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfesoriId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Subjekti")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KontaktiId");

                    b.HasIndex("PrindiId");

                    b.HasIndex("ProfesoriId");

                    b.ToTable("Kontaktet");
                });

            modelBuilder.Entity("Domain.Laburatiori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEKrijimit")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lloji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NrPaisjeve")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LendaId");

                    b.ToTable("Laburatioret");
                });

            modelBuilder.Entity("Domain.Lenda", b =>
                {
                    b.Property<Guid>("LendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEShtimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmriLendes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SyllabusiId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LendaId");

                    b.HasIndex("SyllabusiId");

                    b.ToTable("Lendet");
                });

            modelBuilder.Entity("Domain.Libri", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Autori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Klasa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LendaString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulli")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LendaId");

                    b.ToTable("Librat");
                });

            modelBuilder.Entity("Domain.Njoftimi", b =>
                {
                    b.Property<Guid>("NjoftimiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEShtimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulli")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NjoftimiId");

                    b.ToTable("Njoftimet");
                });

            modelBuilder.Entity("Domain.Nxenesi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfRegistration")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Nxenesit");
                });

            modelBuilder.Entity("Domain.Orari", b =>
                {
                    b.Property<Guid>("OrariId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Enjte1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enjte2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enjte3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enjte4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enjte5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enjte6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hene1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hene2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hene3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hene4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hene5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hene6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("KlasaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Marte1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marte2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marte3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marte4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marte5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marte6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merkure1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merkure2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merkure3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merkure4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merkure5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merkure6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Premte1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Premte2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Premte3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Premte4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Premte5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Premte6")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrariId");

                    b.HasIndex("KlasaID");

                    b.ToTable("Oraret");
                });

            modelBuilder.Entity("Domain.Pajisja", b =>
                {
                    b.Property<Guid>("PajisjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEShtimit")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LaburatioriId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("emriPajisjes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kodiProduktit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PajisjaId");

                    b.HasIndex("LaburatioriId");

                    b.ToTable("Pajisjet");
                });

            modelBuilder.Entity("Domain.Paralelja", b =>
                {
                    b.Property<Guid>("ParaleljaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KapacitetiMax")
                        .HasColumnType("int");

                    b.Property<int>("KapacitetiMin")
                        .HasColumnType("int");

                    b.Property<int>("Numri")
                        .HasColumnType("int");

                    b.HasKey("ParaleljaId");

                    b.ToTable("Paralelet");
                });

            modelBuilder.Entity("Domain.Postimi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Permbajtja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulli")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Postimet");
                });

            modelBuilder.Entity("Domain.Prindi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataLindjes")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Prinderit");
                });

            modelBuilder.Entity("Domain.Profesori", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRegjistrimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("GradaAkademike")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("KlasaKujdestariKlasaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlasaKujdestariKlasaId");

                    b.HasIndex("LendaId");

                    b.ToTable("Profesoret");
                });

            modelBuilder.Entity("Domain.ProfesoriKlasa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KlasaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("KlasaId");

                    b.HasIndex("ProfId");

                    b.ToTable("ProfesoriKlasa");
                });

            modelBuilder.Entity("Domain.Salla", b =>
                {
                    b.Property<Guid>("SallaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmriSalles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasProjector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NrUleseve")
                        .HasColumnType("int");

                    b.HasKey("SallaId");

                    b.ToTable("Sallat");
                });

            modelBuilder.Entity("Domain.Syllabusi", b =>
                {
                    b.Property<Guid>("SyllabusiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEKrijimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmriSyllabusit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkuISyllabusit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SyllabusiId");

                    b.ToTable("Syllabuset");
                });

            modelBuilder.Entity("Domain.Vleresimi", b =>
                {
                    b.Property<Guid>("VleresimiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataRegjistrimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gjysemvjetori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lenda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NxenesiId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfesoriId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Viti")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VleresimiId");

                    b.HasIndex("NxenesiId");

                    b.HasIndex("ProfesoriId");

                    b.ToTable("Vleresimi");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Domain.Familja", b =>
                {
                    b.HasOne("Domain.Nxenesi", "Nxenesi")
                        .WithMany("Familjet")
                        .HasForeignKey("NxenesiId");

                    b.HasOne("Domain.Prindi", "Prindi")
                        .WithMany("Familjet")
                        .HasForeignKey("PrindiId");

                    b.Navigation("Nxenesi");

                    b.Navigation("Prindi");
                });

            modelBuilder.Entity("Domain.FeedbackToNxenesi", b =>
                {
                    b.HasOne("Domain.Profesori", "Profesori")
                        .WithMany("FeedbackToNxenesit")
                        .HasForeignKey("ProfesoriId");

                    b.Navigation("Profesori");
                });

            modelBuilder.Entity("Domain.Klasa", b =>
                {
                    b.HasOne("Domain.Paralelja", "Paralelja")
                        .WithMany("Klasa")
                        .HasForeignKey("ParaleljaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Salla", "Salla")
                        .WithOne("Klasa")
                        .HasForeignKey("Domain.Klasa", "SallaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paralelja");

                    b.Navigation("Salla");
                });

            modelBuilder.Entity("Domain.Kontakti", b =>
                {
                    b.HasOne("Domain.Prindi", "Prindi")
                        .WithMany("Kontaktet")
                        .HasForeignKey("PrindiId");

                    b.HasOne("Domain.Profesori", "Profesori")
                        .WithMany("Kontaktet")
                        .HasForeignKey("ProfesoriId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Prindi");

                    b.Navigation("Profesori");
                });

            modelBuilder.Entity("Domain.Laburatiori", b =>
                {
                    b.HasOne("Domain.Lenda", "Lenda")
                        .WithMany("Laburatoret")
                        .HasForeignKey("LendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lenda");
                });

            modelBuilder.Entity("Domain.Lenda", b =>
                {
                    b.HasOne("Domain.Syllabusi", "Syllabusi")
                        .WithMany("Lendet")
                        .HasForeignKey("SyllabusiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Syllabusi");
                });

            modelBuilder.Entity("Domain.Libri", b =>
                {
                    b.HasOne("Domain.Lenda", "Lenda")
                        .WithMany("Librat")
                        .HasForeignKey("LendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lenda");
                });

            modelBuilder.Entity("Domain.Orari", b =>
                {
                    b.HasOne("Domain.Klasa", "Klasa")
                        .WithMany("Oraret")
                        .HasForeignKey("KlasaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klasa");
                });

            modelBuilder.Entity("Domain.Pajisja", b =>
                {
                    b.HasOne("Domain.Laburatiori", "Laburatiori")
                        .WithMany("Pajisjet")
                        .HasForeignKey("LaburatioriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laburatiori");
                });

            modelBuilder.Entity("Domain.Profesori", b =>
                {
                    b.HasOne("Domain.Klasa", "KlasaKujdestari")
                        .WithMany()
                        .HasForeignKey("KlasaKujdestariKlasaId");

                    b.HasOne("Domain.Lenda", "Lenda")
                        .WithMany("Profesoret")
                        .HasForeignKey("LendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KlasaKujdestari");

                    b.Navigation("Lenda");
                });

            modelBuilder.Entity("Domain.ProfesoriKlasa", b =>
                {
                    b.HasOne("Domain.Klasa", "Klasa")
                        .WithMany("Profesoret")
                        .HasForeignKey("KlasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Profesori", "Profesori")
                        .WithMany("Klaset")
                        .HasForeignKey("ProfId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Klasa");

                    b.Navigation("Profesori");
                });

            modelBuilder.Entity("Domain.Vleresimi", b =>
                {
                    b.HasOne("Domain.Nxenesi", "Nxenesi")
                        .WithMany("Vleresimet")
                        .HasForeignKey("NxenesiId");

                    b.HasOne("Domain.Profesori", "Profesori")
                        .WithMany("Vleresimet")
                        .HasForeignKey("ProfesoriId");

                    b.Navigation("Nxenesi");

                    b.Navigation("Profesori");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.AppAdmin", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.AppAdmin", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AppAdmin", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.AppAdmin", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Klasa", b =>
                {
                    b.Navigation("Oraret");

                    b.Navigation("Profesoret");
                });

            modelBuilder.Entity("Domain.Laburatiori", b =>
                {
                    b.Navigation("Pajisjet");
                });

            modelBuilder.Entity("Domain.Lenda", b =>
                {
                    b.Navigation("Laburatoret");

                    b.Navigation("Librat");

                    b.Navigation("Profesoret");
                });

            modelBuilder.Entity("Domain.Nxenesi", b =>
                {
                    b.Navigation("Familjet");

                    b.Navigation("Vleresimet");
                });

            modelBuilder.Entity("Domain.Paralelja", b =>
                {
                    b.Navigation("Klasa");
                });

            modelBuilder.Entity("Domain.Prindi", b =>
                {
                    b.Navigation("Familjet");

                    b.Navigation("Kontaktet");
                });

            modelBuilder.Entity("Domain.Profesori", b =>
                {
                    b.Navigation("FeedbackToNxenesit");

                    b.Navigation("Klaset");

                    b.Navigation("Kontaktet");

                    b.Navigation("Vleresimet");
                });

            modelBuilder.Entity("Domain.Salla", b =>
                {
                    b.Navigation("Klasa");
                });

            modelBuilder.Entity("Domain.Syllabusi", b =>
                {
                    b.Navigation("Lendet");
                });
#pragma warning restore 612, 618
        }
    }
}
